### ISSUE TITLE
get_iOS_files by deviceID

### ISSUE THREAD

**Issue by cassidyschneider** [WIPACrepo/decotools#19]
In the get_iOS_files function, I think it would be useful to include a parameter to select a specific device ID. This way we could easily separate images taken by each device. Also, it might be useful to be able to exclude a specific device ID. There is one device that has ~15,000 events, but I think this was because the camera wasn't properly covered, so these events wouldn't be useful.

**Comment by jrbourbeau** [comment]
I think this is a great idea! Do you want to have a crack at it?
