### ISSUE TITLE
Bug in fileio.py

### ISSUE THREAD

**Issue by cassidyschneider** [WIPACrepo/decotools#27]
When I try calling get_iOS_files() on a specific phone model or device ID, I get this long error message that I think ultimately has to do with the pandas.concat function. The final line of the error message says: 

  File "/home/cschneider/.virtualenvs/deco/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

**Comment by jrbourbeau** [comment]
That probably means that there aren't any files that have the specified phone model or device ID. What was the line that caused this error?

**Comment by cassidyschneider** [comment]
I called get_iOS_files(start_date='2017-07-27',device_id='D8D8E48D-7D3F-4693-A927-A402CF127D25'). This is Miles' device and calling this worked before the latest update was pushed.

**Comment by jrbourbeau** [comment]
Good catch! I'm getting the same error. I'll submit a PR to fix it
