### ISSUE TITLE
Another bug in get_iOS_files()

### ISSUE THREAD

**Issue by cassidyschneider** [WIPACrepo/decotools#29]
I tried calling get_iOS_files(start_date='2017-07-26',device_id='D8D8E48D-7D3F-4693-A927-A402CF127D25') and I got this error:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Tried testing with a few different device IDs and it's the same problem. Basically, any start_date before 2017-07-27 seemed to be causing errors. And when start_date='2017-07-28' (today's date), no error would occur but I would get back an empty list (even when I manually check and the files do exist).

**Comment by jrbourbeau** [comment]
Yeah, sorry about that. I'll doing another update tonight that fixes this.

**Comment by jrbourbeau** [comment]
Again, sorry about that silly mistake. This should be fixed now! I'll file an issue to add more tests to prevent errors like this from going unnoticed.
