### ISSUE TITLE
String format error in get_iOS_files()

### ISSUE THREAD

**Issue by cassidyschneider** [WIPACrepo/decotools#34]
I tried running decotools.get_iOS_files(device_id='F216114B-8710-4790-A05D-D645C9C79C27',end_date='2017-07-20',n_jobs=20) and this returns an error message that reads "ValueError: Unknown string format."

I've run this same format of code before so I'm not sure what's been changed to now cause this error.

**Comment by jrbourbeau** [comment]
Hey @cschneider6, it looks like there were a few spurious file paths that were causing the date parser to crash. Those files have been removed (thanks @mattmeehan!) and `decotools.get_iOS_files(device_id='F216114B-8710-4790-A05D-D645C9C79C27',end_date='2017-07-20',n_jobs=20)` works without any issue now!
