### ISSUE TITLE
convnet.convert_images raises ValueError if edge check fails

### ISSUE THREAD

**Issue by mattmeehan** [WIPACrepo/decotools#59]
convnet.convert_images raises a ValueError if any of the images passed to it failed the edge check. Here's some example code with the full error message:

```python
import decotools as dt
# Get some image files
image_files = dt.get_android_files(start_date='2016.10.30', end_date='2016.11.07')
# process_image_files calls the convert_images function
images = dt.process_image_files(image_files)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-59e1aa4ad428> in <module>()
----> 1 images = dt.process_image_files(image_files)

/home/mrmeehan/software/decotools/decotools/convnet.py in process_image_files(image_files, size)
     74             images.append(None)
     75
---> 76     scaled_images = convert_images(images)
     77
     78     return scaled_images

/home/mrmeehan/software/decotools/decotools/convnet.py in convert_images(images)
     54         shape:(n_images, n_rows, n_cols, 1)
     55     """
---> 56     images = np.array(images, dtype='float32')
     57     images = np.mean(images/255., axis=-1, keepdims=True)
     58     if len(images.shape) == 3:

ValueError: setting an array element with a sequence.
```

This happens because images that fail the edge check in process_image_files are still added to the image list as None:

https://github.com/WIPACrepo/decotools/blob/35fe00cfa64127c77e6c11d7dd74811b3241a45d/decotools/convnet.py#L68-L74

image is no longer regularly shaped, so numpy can't convert it. An easy fix would be to ignore images that fail the edge check altogether, i.e. don't add anything to the image list. It might be good to have some sort of logging or print message to let the user know which, or at least how many, images failed the edge check. Many images end up failing, so it might be easier to just stick with the number.

**Comment by jrbourbeau** [comment]
Good catch, I'm running into the same issue too. Looks like I was just testing on images that all passed the edge check in `process_image_files`. 

> An easy fix would be to ignore images that fail the edge check altogether, i.e. don't add anything to the image list. It might be good to have some sort of logging or print message to let the user know which, or at least how many, images failed the edge check.

I agree that at the end of the day, we can only use the images that pass the edge filter, so we'll have to get rid of the ones that don't pass.

It might be nice to have a fast way to identify which images didn't pass the edge filter. We could add an option (that's `False` by default) to return a boolean array specifying whether each image passed the edge cut. Or maybe it would be more useful to return an array of indices that correspond to the images that failed the edge filter, not sure.
