### ISSUE TITLE
Move CV validation into fit method

### ISSUE THREAD

**Issue by jrbourbeau** [WIPACrepo/decotools#63]
Currently the `CNN` class has both a `fit` and `fit_with_kfold ` method. The content of these methods is similar. `fit_with_kfold` is just `fit` with `sklearn.model_selection.StratifiedKFold` built into it. 

I'd like to unify these two methods by adding a `cv` parameter to the `fit` method.

@mattmeehan @milesjwinter any objections?

**Comment by milesjwinter** [comment]
Sounds like a good idea to me.

Miles
